### ISSUE TITLE
Change cancel to unsubscribe

### ISSUE THREAD

**Issue by shavyg2** [vitaly-t/sub-events#1]
It will make it compatibility with rxjs.

**Comment by vitaly-t** [comment]
This library follows the proper English. When you do not want a subscription anymore, you `cancel` it. Word `unsubscribe` is both longer and more technical, which doesn't help in any way.

> It will make it compatibility with rxjs.

And why would we need compatibility with RXJS?

**Comment by shavyg2** [comment]
It's a major library for transforming and managing events. Used thru angular, svelte, backend node. Just a suggestion as being compatible helps small frameworks grow if people likes them.

"HahHa"
Typescript helps with autocomplete.

"This library uses proper English"
You can close this issue if not interested

**Comment by vitaly-t** [comment]
I am well familiar with RXJS, I've used it a lot both on the server side and the client side. It serves a bit more generic purpose, unlike this library, which focuses just on events, and making them very easy to track, which is quite complicated in RXJS.

I'm not sure if making naming in this library resemble that of RXJS will be a plus somehow. In fact, I have spent some time arguing why it got nothing to do with RXJS. Perhaps I should add another [WiKi] page, explaining just that.

Anyway, thank you for the suggestion, but I will close it now.

[WiKi]:https://github.com/vitaly-t/sub-events/wiki

**Comment by vitaly-t** [comment]
@shavyg2 

In the after-thought, if somebody really needs compatibility with RXJS, and use `unsubscribe`, it can be done with the existing library like this:

```ts
interface SubscriptionEx extends Subscription {
    unsubscribe(): void;
}

Object.defineProperty(Subscription.prototype, 'unsubscribe', {
    value: function () {
        this.cancel();
    }
});

class CustomEvent<T> extends SubEvent<T> {
    public subscribe(cb: SubFunction<T>, options?: ISubOptions): SubscriptionEx {
        return <SubscriptionEx>super.subscribe(cb, options);
    }
}
```

So that when using your `CustomEvent` class, you will be able to cancel a subscription by calling either `cancel` or `unsubscribe`, whichever you prefer.
