### ISSUE TITLE
Deno Support

### ISSUE THREAD

**Issue by sachaw** [vitaly-t/sub-events#28]
I am currently in the process of migrating my library to Deno https://github.com/meshtastic/meshtastic.js
I have used your library since the beginning and it has been invaluable.

Is porting/extending this library to Deno something they you'd consider?

As this project has no real dependencies, It shouldn't prove to be too difficult

**Comment by vitaly-t** [comment]
I've never used Deno, and not planning to. It is already a fully TypeScript, and without dependencies, which means it should be fairly simple to convert - or is it adding support? (I don't know) for Deno.

**Comment by vitaly-t** [comment]
Closing, due to non-response.
